version: "3.3"

services:
  database:
    hostname: db
    container_name: database
    image: mongo
    restart: always
    networks:
      - network_practica1
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  backend:
    container_name: backend
    restart: always
    build: ./server
    image: mdaniel543/backend_201709450
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - network_practica1

  frontend:
    container_name: frontend
    restart: always
    build: ./client
    image: mdaniel543/frontend_201709450
    ports:
      - "3000:3000"
    stdin_open: true

  ngnix:
    container_name: ngnix
    restart: always
    build: ./ngnix
    image: ngnix
    ports:
      - "3050:80"
    depends_on:
      - backend
      - frontend
    

networks:
  network_practica1: {}
    