version: "3"

services:
  database:
    container_name: database
    restart: always
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  backend:
    container_name: backend
    restart: always
    build: ./server
    image: mdaniel543/backend_201709450
    ports:
      - "8080:8080"
    depends_on:
      - database
    links:
      - database

  frontend:
    container_name: frontend
    restart: always
    build: ./client
    image: mdaniel543/frontend_201709450
    ports:
      - "3000:3000"
    depends_on:
      - backend
    links:
      - backend